const categoriesList = [
    "Beer",
    "Cocktail",
    "Cocoa",
    "Coffee / Tea",
    "Homemade Liqueur",
    "Ordinary Drink",
    "Other / Unknown",
    "Punch / Party Drink",
    "Shake",
    "Shot",
    "Soft Drink",
];

const glassesList = [
    "Balloon Glass",
    "Beer Glass",
    "Beer Mug",
    "Beer Pilsner",
    "Brandy Snifter",
    "Champagne Flute",
    "Cocktail Glass",
    "Coffee Mug",
    "Collins Glass",
    "Copper Mug",
    "Cordial Glass",
    "Coupe Glass",
    "Highball Glass",
    "Hurricane Glass",
    "Irish Coffee Cup",
    "Jar",
    "Margarita Glass",
    "Margarita / Coupette Glass",
    "Martini Glass",
    "Mason Jar",
    "Nick and Nora Glass",
    "Old-Fashioned Glass",
    "Pint Glass",
    "Pitcher",
    "Pousse Cafe Glass",
    "Punch Bowl",
    "Shot Glass",
    "Whiskey Glass",
    "Whiskey Sour Glass",
    "White Wine Glass",
    "Wine Glass",
];

const alcoholicList = ["Alcoholic", "Non alcoholic"];

const categoriesUaList = [
    "Пиво",
    "Коктейль",
    "Какао",
    "Кава / Чай",
    "Домашній лікер",
    "Звичайний напій",
    "Інше / Невідомо",
    "Пунш / Напій для вечірки",
    "Шейк",
    "Шот",
    "Безалкогольний напій",
];

const glassesUaList = [
    "Склянка-колба",
    "Келих для пива",
    "Пивний кухоль",
    "Келих для пива Pilsner",
    "Склянка для бренді",
    "Флейта для шампанського",
    "Склянка для коктейлів",
    "Кружка для кави",
    "Склянка циліндричної форми",
    "Мідний кухоль",
    "Склянка для лікеру",
    "Склянка куп",
    "Склянка для коктейлів Хайбол",
    "Склянка для коктейлів Гаррікейн",
    "Чашка для ірландської кави",
    "Банка",
    "Склянка для маргарити",
    "Склянка для маргарити або купетта",
    "Склянка для мартіні",
    "Банка для Мейсона",
    "Склянка Ніка та Нори",
    "Стакан для старомодних напоїв",
    "Пінтовий стакан",
    "Глечик",
    "Склянка для пусс кави",
    "Чаша для пуншу",
    "Рюмка",
    "Склянка для віскі",
    "Склянка для віскі Сауер",
    "Келих для білого вина",
    "Келих для вина",
];

const alcoholicUaList = ["Алкогольний", "Безалкогольний"];

module.exports = {
    categoriesList, glassesList, alcoholicList,
    categoriesUaList, glassesUaList, alcoholicUaList
}