const categoriesList = [
    "Beer",
    "Cocktail",
    "Cocoa",
    "Coffee / Tea",
    "Homemade Liqueur",
    "Ordinary Drink",
    "Other/Unknown",
    "Punch / Party Drink",
    "Shake",
    "Shot",
    "Soft Drink",
];

const glassesList = [
    "Balloon Glass",
    "Beer Glass",
    "Beer Mug",
    "Beer Pilsner",
    "Brandy Snifter",
    "Champagne Flute",
    "Cocktail Glass",
    "Coffee Mug",
    "Collins Glass",
    "Copper Mug",
    "Cordial Glass",
    "Coupe Glass",
    "Highball Glass",
    "Hurricane glass",
    "Irish Coffee Cup",
    "Jar",
    "Margarita Glass",
    "Margarita/Coupette glass",
    "Martini Glass",
    "Mason Jar",
    "Nick and Nora Glass",
    "Old-Fashioned Glass",
    "Pint Glass",
    "Pitcher",
    "Pousse Cafe Glass",
    "Punch Bowl",
    "Shot Glass",
    "Whiskey Glass",
    "Whiskey Sour Glass",
    "White Wine Glass",
    "Wine Glass",
];

const alcoholicList = ["Alcoholic", "Non alcoholic"];

module.exports = { categoriesList, glassesList, alcoholicList }